name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Code & Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Check code syntax
        run: npm run check
